name = "DownstreamFail"
uuid = "4791af83-954e-4493-a6a8-9d4cf0982339"
authors = ["Ciarán O'Mara <Ciaran.OMara@utas.edu.au>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
